src/carts/urls.py
from django.conf.urls import url
from .views import (cart_home, cart_update, checkout_home, checkout_done_view)

urlpatterns = [
    url(r'^$', cart_home, name='home'),
    url(r'^checkout/$', checkout_home, name='checkout'),
    url(r'^checkout/success/$', checkout_done_view, name='success'),
    url(r'^update/$', cart_update, name='update'),

]

src/ecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LogoutView 
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView, RedirectView
# from products.views import (ProductListView, product_list_view, ProductDetailView, 
#                             product_detail_view,
#                             ProductFeaturedListView, ProductFeaturedDetailView, ProductDetailSlugView)

from carts.views import cart_home, cart_detail_api_view
from marketing.views import MarketingPreferenceUpdateView, MailchimpWebHookView
from orders.views import LibraryView
from accounts.views import LoginView, RegisterView, GuestRegisterView 
from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from analytics.views import SalesView, SalesAjaxView
from billing.views import payment_method_view, payment_method_createview
from .views import home_page, about_page, contact_page, profile_page

urlpatterns = [
    url(r'^$', home_page, name='home'),
    url(r'^about/$', about_page, name='about'),
    #url(r'^accounts/login/$', about_page, name='about'),
    url(r'^accounts/login/$', RedirectView.as_view(url='/account')),
    url(r'^account/', include("accounts.urls", namespace='account')),
    url(r'^accounts/', include("accounts.passwords.urls")),
    url(r'^contact/$', contact_page, name='contact'),
    url(r'^profile/$', profile_page, name='profile'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^checkout/address/create/$', checkout_address_create_view, name='checkout_address_create'),
    url(r'^checkout/address/reuse/$', checkout_address_reuse_view, name='checkout_address_reuse'),
    url(r'^analytics/sales/$', SalesView.as_view(), name='sales-analytics'),
    url(r'^analytics/sales/data/$', SalesAjaxView.as_view(), name='sales-analytics-data'),
    url(r'^register/guest/$', GuestRegisterView.as_view(), name='guest_register'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^api/cart/$', cart_detail_api_view, name='api-cart'),
    url(r'^cart/', include("carts.urls", namespace='cart')),
    url(r'^billing/payment-method/$', payment_method_view, name='billing-payment-method'),
    url(r'^billing/payment-method/create/$', payment_method_createview, name='billing-payment-method-endpoint'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^bootstrap/$', TemplateView.as_view(template_name='bootstrap/example.html')),
    url(r'^library/$', LibraryView.as_view(), name='library'),
    url(r'^orders/', include("orders.urls", namespace='orders')),
    url(r'^products/', include("products.urls", namespace='products')),
    url(r'^search/', include("search.urls", namespace='search')),
    url(r'^settings/$', RedirectView.as_view(url='/account')),
    url(r'^settings/email/$', MarketingPreferenceUpdateView.as_view(), name='marketing-pref'),
    url(r'^webhooks/mailchimp/$', MailchimpWebHookView.as_view(), name='webhooks-mailchimp'),


    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/base/css.html
{% load static %}

<!--Bootstrap CSS-->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" 
integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" 
crossorigin="anonymous">


<!--<link rel = 'stylesheet' href='{% static "css/main.css"%}'>-->


<!-- Fontawesome CSS-->
<link rel = 'stylesheet' href='https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' />


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">


<!-- Stripe CSS-->
<link rel="stylesheet" href ="{%static 'css/stripe-custome-style.css' %}"

src/templates/base/forms.html
{% extends "base.html" %}
{% block content %}
    <div class='col-12 col-md-6 mx-auto'>
        {% if title %}<h1 class = 'my-3'>{{title}}</h1>{% endif %}
        <form method = "POST" action='{% if action_url %}{{action_url}}{% endif %}'> {% csrf_token %}
            {% if next_url %}
                <input type='hidden' name='next' value='{{ next_url }}' />
            {% endif %}
        {{form.as_p}}
        <button type = "submit" class = "btn btn-default">Save</button>
        </form>
    </div>
{% endblock %}

src/templates/base/js.html
{% load static%}

<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>


<!-- jsrender -->
<script src ='https://cdnjs.cloudflare.com/ajax/libs/jsrender/1.0.6/jsrender.min.js'></script>

<script src='https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js'></script>

{% include 'base/js_templates.html' %}
<!-- eCommerce custome JS-->

<script src ='{%static "js/ecommerce.js" %}'></script>


<script src ='{%static "js/ecommerce.sales.js" %}'></script>


<!-- Eccomerce main js -->
<script src ='{%static "js/ecommerce.main.js" %}'></script>


<!-- Django Secure AJAX JS-->
<script src ='{%static "js/csrf.ajax.js" %}'></script>



<!-- Strip JS-->
<script src="https://js.stripe.com/v3/"></script>

src/templates/base/js_templates.html
{% verbatim %}
        <!-- stripe template form -->
        <script id = "stripeTemplate" type="text/x-jsrender">
            <form class='payment-form' action="" method="POST" id="payment-form" data-token='{{:publish_key}}' data-next-url='{{:next_url}}'>
                <div class="form-row">
                <!-- <label for="card-element">
                    Credit or debit card
                </label> -->
                <div id="card-element" class='form-control'>
                    <!-- A Stripe Element will be inserted here. -->
                </div>
            
                <!-- Used to display Element errors. -->
                <div id="card-errors" role="alert"></div>
                </div>
            
                <button class ='btn btn-primary my-3 btn-load'>{{:btn_title}}</button>
            </form>
        </script>
{% endverbatim %}

src/templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'products:list' as product_list_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}
{% url 'accounts:home' as account_url %}
{% url 'cart:home' as cart_url %}


<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3 ">
  <div class = 'container'>
    <a class = 'navbar-brand' href="{{home_url}}">
      <img src="http://www.getbootstrap.com/docs/4.5/assets/brand/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">
      {% if brand_name %} {{brand_name}} {% else %} eCommerce {%endif%}
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item {% if request.path == home_url%}active{% endif %}">
          <a class="nav-link" href="{{home_url}}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item {% if request.path == contact_url%}active{% endif %}">
          <a class="nav-link" href="{{contact_url}}">Contacts</a>
        </li>
        
        <li class="nav-item {% if request.path == product_list_url%}active{% endif %}">
          <a class="nav-link" href="{{product_list_url}}">Products</a>
        </li>

        {%if request.user.is_authenticated%}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Account
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item  {% if request.path == account_url%}active{% endif %}" href="{{ account_url }}">Home</a>
                <a class="dropdown-item" href="{% url 'account:user-product-history'%}">History</a>
                <a class="dropdown-item" href="#">Billing</a>
                <a class="dropdown-item" href="{% url 'library' %}">Library</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{{logout_url}}">Logout</a>
              </div>
            </li>
        {%else%}
            <li class="nav-item {% if request.path == register_url%}active{% endif %}" >
                <a class="nav-link" href="{{register_url}}">Register</a>
            </li>
            <li class="nav-item {% if request.path == login_url%}active{% endif %}" >
                <a class="nav-link" href="{{login_url}}">Login</a>
            </li>
        {%endif%}
        <li class="nav-item {% if request.path == cart_url%}active{% endif %}" >
          <a class="nav-link" href="{{ cart_url }}"><span class = "navbar-cart-count">{{ request.session.cart_items }}</span> <i class="fa fa-shopping-cart" aria-hidden="true"></i></a>
        </li>
      </ul>
      {% include 'search/snippets/search-form.html' %}
    </div>
    </div>
</nav>


<!-- <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Dropdown
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
      <a class="dropdown-item" href="#">Action</a>
      <a class="dropdown-item" href="#">Another action</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="#">Something else here</a>
    </div>
  </li> -->